# if enum, ensure that it resolves to one of the enumerated values
# ensure that quotation remains the same as in source (either all or none quoted)
#   print warning if source is inconsistent
# ensure prefix
# need custom handling for specialties
from typing import Iterable

from ._file_targets import TARGET_SETS
from ._member_def import MemberDef


def _validation_lines() -> Iterable[str]:
    yield f'# File automatically generated by {__file__.split('src\\')[1]}'
    for target_set in TARGET_SETS:
        yield f'# Automatically generated from {target_set.file_path}'
        yield from target_set.to_lines(MemberDef.literal_lines)


def _write(path: str) -> None:
    with open(path, 'w') as file:
        file.write('\n\n'.join(_validation_lines()))