from typing import Iterable

from ._file_targets import TARGET_SETS
from ._member_def import MemberDef


def _init_lines() -> Iterable[str]:
    yield '# File automatically generated by warno_mfw.hints._generate._literal_lines.py'
    yield 'from .paths import *'
    yield ''
    for target_set in TARGET_SETS:
        yield f'# Automatically generated from {target_set.file_path}'
        yield from target_set.to_lines(MemberDef.literal_line)

def _write(path: str) -> None:
    with open(path, 'w') as file:
        file.write('\n\n'.join(_init_lines()))