# File automatically generated by warno_mfw\hints\_generate\_line_generators.py

from warno_mfw.hints._generate._constants._resolvers import _enum_resolver, _format_resolver

# Automatically generated from GameData/Generated/Gameplay/Gfx/Infanterie/GeneratedDepictionInfantry.ndf

def _resolve_WeaponType(s: str) -> str:
	return _enum_resolver(s, 'WeaponType', None, {'smg': "'smg'", 'bazooka': "'bazooka'", 'mmg': "'mmg'", 'grenade': "'grenade'"})

# Automatically generated from GameData/Generated/Gameplay/Gfx/MissileCarriage.ndf

def _resolve_PylonSet(s: str) -> str:
	return _enum_resolver(s, 'PylonSet', None, {'Vehicle_Default': '~/DepictionPylonSet_Vehicle_Default', 'Vehicle_Default_Showroom': '~/DepictionPylonSet_Vehicle_Default_Showroom', 'ATGM': '~/DepictionPylonSet_ATGM', 'ATGM_Showroom': '~/DepictionPylonSet_ATGM_Showroom', 'Helico_Default': '~/DepictionPylonSet_Helico_Default', 'Helico_Default_Showroom': '~/DepictionPylonSet_Helico_Default_Showroom', 'Helico_SOV': '~/DepictionPylonSet_Helico_SOV', 'Helico_SOV_Showroom': '~/DepictionPylonSet_Helico_SOV_Showroom', 'Airplane_FR': '~/DepictionPylonSet_Airplane_FR', 'Airplane_FR_Showroom': '~/DepictionPylonSet_Airplane_FR_Showroom', 'Airplane_Default': '~/DepictionPylonSet_Airplane_Default', 'Airplane_Default_Showroom': '~/DepictionPylonSet_Airplane_Default_Showroom', 'Airplane_US': '~/DepictionPylonSet_Airplane_US', 'Airplane_US_Showroom': '~/DepictionPylonSet_Airplane_US_Showroom', 'Airplane_RFA': '~/DepictionPylonSet_Airplane_RFA', 'Airplane_RFA_Showroom': '~/DepictionPylonSet_Airplane_RFA_Showroom', 'Airplane_UK': '~/DepictionPylonSet_Airplane_UK', 'Airplane_UK_Showroom': '~/DepictionPylonSet_Airplane_UK_Showroom', 'Airplane_SOV': '~/DepictionPylonSet_Airplane_SOV', 'Airplane_SOV_Showroom': '~/DepictionPylonSet_Airplane_SOV_Showroom'})

# Automatically generated from GameData/Generated/Gameplay/Gfx/UniteDescriptor.ndf

def _resolve_AcknowUnitType(s: str) -> str:
	return _enum_resolver(s, 'AcknowUnitType', None, {'SAM': '~/TAcknowUnitType_SAM', 'CanonAA': '~/TAcknowUnitType_CanonAA', 'GunArtillery': '~/TAcknowUnitType_GunArtillery', 'ArtShell': '~/TAcknowUnitType_ArtShell', 'Transport': '~/TAcknowUnitType_Transport', 'Tank': '~/TAcknowUnitType_Tank', 'Command': '~/TAcknowUnitType_Command', 'Reco': '~/TAcknowUnitType_Reco', 'TankDestroyer': '~/TAcknowUnitType_TankDestroyer', 'TankDestroyerMissile': '~/TAcknowUnitType_TankDestroyerMissile', 'Inf': '~/TAcknowUnitType_Inf', 'Inf2': '~/TAcknowUnitType_Inf2', 'Engineer': '~/TAcknowUnitType_Engineer', 'Logistic': '~/TAcknowUnitType_Logistic', 'Recon_INF': '~/TAcknowUnitType_Recon_INF', 'MLRS': '~/TAcknowUnitType_MLRS', 'Recon_Vehicle': '~/TAcknowUnitType_Recon_Vehicle', 'CommandVehicle': '~/TAcknowUnitType_CommandVehicle', 'Command_Infantry': '~/TAcknowUnitType_Command_Infantry', 'Inf_Elite': '~/TAcknowUnitType_Inf_Elite', 'Inf_Militia': '~/TAcknowUnitType_Inf_Militia', 'KaJaPa': '~/TAcknowUnitType_KaJaPa', 'Vehicle': '~/TAcknowUnitType_Vehicle', 'HeliAttack': '~/TAcknowUnitType_HeliAttack', 'HeliTransport': '~/TAcknowUnitType_HeliTransport', 'GroundAtk': '~/TAcknowUnitType_GroundAtk', 'Air_CAS': '~/TAcknowUnitType_Air_CAS', 'AirSup': '~/TAcknowUnitType_AirSup', 'Multirole': '~/TAcknowUnitType_Multirole'})

def _resolve_MotherCountry(s: str) -> str:
	return _format_resolver(s, '', True)

def _resolve_Coalition(s: str) -> str:
	return _enum_resolver(s, 'Coalition', {'PACT': 'Axis', 'NATO': 'Allied'}, {'Axis': 'ECoalition/Axis', 'Allied': 'ECoalition/Allied'})

def _resolve_TypeUnitFormation(s: str) -> str:
	return _enum_resolver(s, 'TypeUnitFormation', None, {'Artillerie': "'Artillerie'", 'Char': "'Char'", 'Supply': "'Supply'", 'Reconnaissance': "'Reconnaissance'", 'None': "'None'"})

def _resolve_Factory(s: str) -> str:
	return _enum_resolver(s, 'Factory', {'ART': 'Art', 'AA': 'DCA', 'HEL': 'Helis', 'INF': 'Infantry', 'LOG': 'Logistic', 'AIR': 'Planes', 'REC': 'Recons', 'TNK': 'Tanks'}, {'DCA': 'EDefaultFactories/DCA', 'Art': 'EDefaultFactories/Art', 'Tanks': 'EDefaultFactories/Tanks', 'Logistic': 'EDefaultFactories/Logistic', 'Recons': 'EDefaultFactories/Recons', 'Infantry': 'EDefaultFactories/Infantry', 'Helis': 'EDefaultFactories/Helis', 'Planes': 'EDefaultFactories/Planes'})

def _resolve_InfoPanelConfigurationToken(s: str) -> str:
	return _enum_resolver(s, 'InfoPanelConfigurationToken', None, {'Default': "'Default'", 'VehiculeTransporter': "'VehiculeTransporter'", 'Infantry': "'Infantry'", 'VehiculeSupplier': "'VehiculeSupplier'", 'HelicoTransporter': "'HelicoTransporter'", 'HelicoDefault': "'HelicoDefault'", 'HelicoSupplier': "'HelicoSupplier'", 'avion': "'avion'"})

def _resolve_MenuIconTexture(s: str) -> str:
	return _format_resolver(s, 'Texture_RTS_H_', True)

def _resolve_PrimarySpecialty(s: str) -> str:
	return _enum_resolver(s, 'PrimarySpecialty', None, {'AA': "'AA'", 'howitzer': "'howitzer'", 'mortar': "'mortar'", 'transport': "'transport'", 'ifv': "'ifv'", 'hq_veh': "'hq_veh'", 'reco': "'reco'", 'hq_tank': "'hq_tank'", 'armor': "'armor'", 'AT': "'AT'", 'infantry': "'infantry'", 'hq_inf': "'hq_inf'", 'engineer': "'engineer'", 'supply': "'supply'", 'mlrs': "'mlrs'", 'Armor_heavy': "'Armor_heavy'", 'appui': "'appui'", 'hel_reco': "'hel_reco'", 'hq_helo': "'hq_helo'", 'sead': "'sead'", 'uav': "'uav'"})

def _resolve_SecondarySpecialty(s: str) -> str:
	return _enum_resolver(s, 'SecondarySpecialty', None, {'amphibie': "'_amphibie'", 'reservist': "'_reservist'", 'para': "'_para'", 'transport2': "'_transport2'", 'smoke_launcher': "'_smoke_launcher'", 'transport1': "'_transport1'", 'ifv': "'_ifv'", 'leader': "'_leader'", 'eo_dazzler': "'_eo_dazzler'", 'era': "'_era'", 'resolute': "'_resolute'", 'choc': "'_choc'", 'security': "'_security'", 'mp': "'_mp'", 'sf': "'_sf'", 'falseflag': "'_falseflag'", 'canBeAirlifted': "'_canBeAirlifted'", 'gsr': "'_gsr'", 'singint': "'_singint'", 'fireDirection': "'_fireDirection'", 'sniper': "'_sniper'", 'airlift': "'_airlift'", 'jammer': "'_jammer'", 'electronic_warfare': "'_electronic_warfare'"})

def _resolve_TypeStrategicCount(s: str) -> str:
	return _enum_resolver(s, 'TypeStrategicCount', None, {'AA': 'ETypeStrategicDetailedCount/AA', 'Howitzer': 'ETypeStrategicDetailedCount/Howitzer', 'Mortar': 'ETypeStrategicDetailedCount/Mortar', 'Support': 'ETypeStrategicDetailedCount/Support', 'Ifv': 'ETypeStrategicDetailedCount/Ifv', 'CMD_Veh': 'ETypeStrategicDetailedCount/CMD_Veh', 'Reco_Veh': 'ETypeStrategicDetailedCount/Reco_Veh', 'CMD_Tank': 'ETypeStrategicDetailedCount/CMD_Tank', 'Armor': 'ETypeStrategicDetailedCount/Armor', 'AT_Veh': 'ETypeStrategicDetailedCount/AT_Veh', 'Reco': 'ETypeStrategicDetailedCount/Reco', 'AA_Veh': 'ETypeStrategicDetailedCount/AA_Veh', 'AT_Gun': 'ETypeStrategicDetailedCount/AT_Gun', 'Infantry': 'ETypeStrategicDetailedCount/Infantry', 'AT': 'ETypeStrategicDetailedCount/AT', 'CMD_Inf': 'ETypeStrategicDetailedCount/CMD_Inf', 'Engineer': 'ETypeStrategicDetailedCount/Engineer', 'Reco_Inf': 'ETypeStrategicDetailedCount/Reco_Inf', 'Supply': 'ETypeStrategicDetailedCount/Supply', 'Mlrs': 'ETypeStrategicDetailedCount/Mlrs', 'Transport': 'ETypeStrategicDetailedCount/Transport', 'Armor_Heavy': 'ETypeStrategicDetailedCount/Armor_Heavy', 'Manpad': 'ETypeStrategicDetailedCount/Manpad', 'Hel_Transport': 'ETypeStrategicDetailedCount/Hel_Transport', 'Hel_Support': 'ETypeStrategicDetailedCount/Hel_Support', 'AT_Hel': 'ETypeStrategicDetailedCount/AT_Hel', 'Reco_Hel': 'ETypeStrategicDetailedCount/Reco_Hel', 'CMD_Hel': 'ETypeStrategicDetailedCount/CMD_Hel', 'Supply_Hel': 'ETypeStrategicDetailedCount/Supply_Hel', 'AA_Hel': 'ETypeStrategicDetailedCount/AA_Hel', 'Air_AT': 'ETypeStrategicDetailedCount/Air_AT', 'Air_Support': 'ETypeStrategicDetailedCount/Air_Support', 'Air_Sead': 'ETypeStrategicDetailedCount/Air_Sead', 'Air_AA': 'ETypeStrategicDetailedCount/Air_AA'})

def _resolve_UnitRole(s: str) -> str:
	return _enum_resolver(s, 'UnitRole', None, {'tank_A': "'tank_A'", 'tank_B': "'tank_B'", 'tank_C': "'tank_C'", 'tank_D': "'tank_D'"})